// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_KEY']!,
    appId: '1:1068670035033:web:b73157af91c4d7de2cbd48',
    messagingSenderId: '1068670035033',
    projectId: 'inhacarpool-b190f',
    authDomain: 'inhacarpool-b190f.firebaseapp.com',
    storageBucket: 'inhacarpool-b190f.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_KEY']!,
    appId: '1:1068670035033:android:30fbc48892f5569d2cbd48',
    messagingSenderId: '1068670035033',
    projectId: 'inhacarpool-b190f',
    storageBucket: 'inhacarpool-b190f.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_KEY']!,
    appId: '1:1068670035033:ios:b1f43d8b555dd7b62cbd48',
    messagingSenderId: '1068670035033',
    projectId: 'inhacarpool-b190f',
    storageBucket: 'inhacarpool-b190f.appspot.com',
    iosClientId: '1068670035033-6i00df4tcfta4t19rtu1oga2git2u0np.apps.googleusercontent.com',
    iosBundleId: 'com.objects.inha-carpool',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_KEY']!,
    appId: '1:1068670035033:ios:53db38e0874c0d0b2cbd48',
    messagingSenderId: '1068670035033',
    projectId: 'inhacarpool-b190f',
    storageBucket: 'inhacarpool-b190f.appspot.com',
    iosClientId: '1068670035033-2es4dqka3b5uofkqfjv80cqa6kjq9knc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
